version: "3.9"

services:
  vue-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home_web
    ports:
      - "80:80"
    networks:
      - home-monitoring
    restart: always

networks:
  home-monitoring:
    external: true
