server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://java-server:9000; # ip 대신 docker 컨테이너 명 기재
    }
}
